Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/FileName:
  Exclude:
    - exe/*

Style/SpaceBeforeBlockBraces:
  EnforcedStyle: no_space

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
